spring:
  datasource:
    url: jdbc:h2:mem:gym_crm_test
    username: sa

  jpa:
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: ERROR