services:
  eureka-server:
    build:
      context: ${EUREKA_SERVER_PATH}
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    networks:
      - microservices-net

  trainer-workload-service:
    build:
      context: ${TRAINER_WORKLOAD_PATH}
    ports:
      - "${TRAINER_WORKLOAD_PORT}:${TRAINER_WORKLOAD_PORT}"
    depends_on:
      - eureka-server
    networks:
      - microservices-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_DEFAULT_ZONE}

  gym-crm:
    build:
      context: ${GYM_CRM_PATH}
    ports:
      - "${GYM_CRM_PORT}:${GYM_CRM_PORT}"
    depends_on:
      - eureka-server
      - trainer-workload-service
    networks:
      - microservices-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_DEFAULT_ZONE}

networks:
  microservices-net:
    driver: bridge
