spring:
  application:
    name: trainer-workload-service

  data:
    mongodb:
      database: trainer-workload
      port: 27017
      host: localhost
      uri: mongodb://root:root@localhost:27017/?authSource=admin
      auto-index-creation: true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8081

jwt:
  secret: aslfkjaslkdnrfuioqenrkqndlvjdnavkjdsnfldkjsn

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
